### Editar un libro (POST)

# Simular POST con nuevos datos del libro

PUT http://localhost:5000/actualizar_libro/14
Content-Type: application/json

{
  "titulo": "Generaciones de Flask",
  "autor": "Maria Lopez"
}
