### Editar un libro (POST)

# Simular POST con nuevos datos del libro

PUT http://localhost:5000/libro/11
Content-Type: application/json

{
  "titulo": "Generaciones de Flask",
  "autor": "Juan Perez"
}
